name: cs273b
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py36h8c4c3a4_2
  - async_generator=1.10=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py36he6145b8_1001
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py36h9880bd3_2
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36h9880bd3_1008
  - cryptography=3.1.1=py36h5d711a5_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36h9f0ad1d_1002
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py36hac0dd68_1
  - ipython=5.8.0=py36_1
  - ipython_genutils=0.2.0=py_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py36h9f0ad1d_2
  - jupyterlab=2.2.8=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libsodium=1.0.18=h516909a_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py36he6145b8_2
  - mistune=0.8.4=py36h8c4c3a4_1002
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.7=py36h9f0ad1d_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.1=py_0
  - notebook=6.1.4=py36h9f0ad1d_0
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandoc=2.11.0.1=hd18ef5c_0
  - pandocfilters=1.4.2=py_1
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=20.2.3=py36_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt_toolkit=1.0.15=py_1
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py36h8c4c3a4_1
  - pysocks=1.7.1=py36h9880bd3_2
  - python=3.6.12=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pyzmq=19.0.2=py36h9947dbf_2
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - send2trash=1.5.0=py_0
  - setuptools=50.3.0=py36hb0f4dca_1
  - simplegeneric=0.8.1=py_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.1=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.0.4=py36h8c4c3a4_2
  - traitlets=4.3.3=py36h9f0ad1d_1
  - urllib3=1.25.10=py_0
  - viennarna=2.4.15=py36hd181a71_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he1b5a44_2
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - appdirs==1.4.4
    - biopython==1.78
    - cycler==0.10.0
    - forgi==2.0.2
    - future==0.18.2
    - kiwisolver==1.2.0
    - logging-exceptions==0.1.8
    - matplotlib==3.3.2
    - networkx==2.5
    - numpy==1.19.2
    - pandas==1.1.3
    - pillow==8.0.0
    - pytz==2020.1
    - scipy==1.5.2
    - seaborn==0.11.0
prefix: /home/schlager/miniconda3/envs/cs273b
